In [3]:
import pandas as pd

In [4]:
#crear dataframe
#data={"":[,,,]}

data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

In [5]:
#pd.DataFrame(datos)
df = pd.DataFrame(data)

print(df) 

   calories  duration
0       420        50
1       380        40
2       390        45


In [6]:
#type(algo)
print(type(df))
#df.shape
print(df.shape)

<class 'pandas.core.frame.DataFrame'>
(3, 2)


In [11]:
#primera columna
primera=df.iloc[:,0]
print(primera)
primera1=df.iloc[:,0:2]
print(primera1)
primera2=df.iloc[1]
print(primera2)
primera3=df.iloc[1:3]
print(primera3)

0    420
1    380
2    390
Name: calories, dtype: int64
   calories  duration
0       420        50
1       380        40
2       390        45
calories    380
duration     40
Name: 1, dtype: int64
   calories  duration
1       380        40
2       390        45


In [12]:
#eliminar columna
df1=df.drop(columns=["calories"])
print(df1)

   duration
0        50
1        40
2        45


In [13]:
import numpy as np

In [14]:
#crear array
#np.array([[,,,],[]])
arr = np.array([[0, 1, 2], [3, 4, 5]]) 

In [15]:
print(arr)

print(type(arr))

[[0 1 2]
 [3 4 5]]
<class 'numpy.ndarray'>


In [16]:
print(arr.shape)

(2, 3)


In [17]:
#reshape
array_nuevo=arr.reshape(3,2)
print(array_nuevo)

[[0 1]
 [2 3]
 [4 5]]


In [18]:
#convertir
df1=pd.DataFrame(array_nuevo,columns=["primer","segun"])

In [19]:
print(df1)

   primer  segun
0       0      1
1       2      3
2       4      5


In [21]:
nmp=df1.to_numpy()
print(type(nmp))
print(nmp)

<class 'numpy.ndarray'>
[[0 1]
 [2 3]
 [4 5]]
