In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler


In [2]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data"

In [3]:
cabecera = ['clase', 'Alcohol', 'Malic acid', 'Ash', 'Alcalinity of ash', 'Magnesium', 'Total phenols', 'Flavanoids', 'Nonflavanoid phenols', 
            'Proanthocyanins', 'Color intensity', 'Hue', 'OD280/OD315 of diluted wines', 'Proline'] 


In [4]:
datos = pd.read_csv(url, sep=',', header=None)
datos

0      1     2     3     4    5     6     7     8     9      10    11  \
0     1  14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29   5.64  1.04   
1     1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28   4.38  1.05   
2     1  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81   5.68  1.03   
3     1  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18   7.80  0.86   
4     1  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82   4.32  1.04   
..   ..    ...   ...   ...   ...  ...   ...   ...   ...   ...    ...   ...   
173   3  13.71  5.65  2.45  20.5   95  1.68  0.61  0.52  1.06   7.70  0.64   
174   3  13.40  3.91  2.48  23.0  102  1.80  0.75  0.43  1.41   7.30  0.70   
175   3  13.27  4.28  2.26  20.0  120  1.59  0.69  0.43  1.35  10.20  0.59   
176   3  13.17  2.59  2.37  20.0  120  1.65  0.68  0.53  1.46   9.30  0.60   
177   3  14.13  4.10  2.74  24.5   96  2.05  0.76  0.56  1.35   9.20  0.61   

       12    13  
0    3.92  1065  
1    3.40  1050  
2    3.17  1185  
3    3.45  1480  
4    2.93   735  
..    ...   ...  
173  1.74   740  
174  1.56   750  
175  1.56   835  
176  1.62   840  
177  1.60   560  

[178 rows x 14 columns]

In [5]:
datos.columns=cabecera
datos

clase  Alcohol  Malic acid   Ash  Alcalinity of ash  Magnesium  \
0        1    14.23        1.71  2.43               15.6        127   
1        1    13.20        1.78  2.14               11.2        100   
2        1    13.16        2.36  2.67               18.6        101   
3        1    14.37        1.95  2.50               16.8        113   
4        1    13.24        2.59  2.87               21.0        118   
..     ...      ...         ...   ...                ...        ...   
173      3    13.71        5.65  2.45               20.5         95   
174      3    13.40        3.91  2.48               23.0        102   
175      3    13.27        4.28  2.26               20.0        120   
176      3    13.17        2.59  2.37               20.0        120   
177      3    14.13        4.10  2.74               24.5         96   

     Total phenols  Flavanoids  Nonflavanoid phenols  Proanthocyanins  \
0             2.80        3.06                  0.28             2.29   
1             2.65        2.76                  0.26             1.28   
2             2.80        3.24                  0.30             2.81   
3             3.85        3.49                  0.24             2.18   
4             2.80        2.69                  0.39             1.82   
..             ...         ...                   ...              ...   
173           1.68        0.61                  0.52             1.06   
174           1.80        0.75                  0.43             1.41   
175           1.59        0.69                  0.43             1.35   
176           1.65        0.68                  0.53             1.46   
177           2.05        0.76                  0.56             1.35   

     Color intensity   Hue  OD280/OD315 of diluted wines  Proline  
0               5.64  1.04                          3.92     1065  
1               4.38  1.05                          3.40     1050  
2               5.68  1.03                          3.17     1185  
3               7.80  0.86                          3.45     1480  
4               4.32  1.04                          2.93      735  
..               ...   ...                           ...      ...  
173             7.70  0.64                          1.74      740  
174             7.30  0.70                          1.56      750  
175            10.20  0.59                          1.56      835  
176             9.30  0.60                          1.62      840  
177             9.20  0.61                          1.60      560  

[178 rows x 14 columns]

## ESCALADO DE LOS DATOS¶

In [6]:
X = MinMaxScaler().fit_transform(datos.iloc[:, 1:])
y = np.array(datos.iloc[:,0])

In [9]:
type(X), type(y), X.shape, y.shape, np.min(X, axis=0), np.max(X, axis=0), np.unique(y)

(numpy.ndarray,
 numpy.ndarray,
 (178, 13),
 (178,),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([1, 2, 3]))

## DATOS DE ENTRENAMIENTO Y TEST - ESTRATIFICADOS

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=1/3, stratify=y, random_state=0)

# K-MEANS - CENTROS

In [11]:
from sklearn.cluster import KMeans
kmedias = KMeans(n_clusters=6).fit(X_train)
centros = kmedias.cluster_centers_
#hago kmenas con un solo train
#busco sus centros

In [13]:
centros.shape

(6, 13)

# Matriz de DISTANCIAS - SIGMA

In [14]:
from sklearn.metrics.pairwise import euclidean_distances
distancias = euclidean_distances(centros)
distancias
#matriz de distancias sobre los centros

array([[0.        , 1.08841982, 0.97755944, 0.66658867, 0.73973161,
        0.5616437 ],
       [1.08841982, 0.        , 0.8102114 , 1.13049335, 0.79503927,
        1.19712465],
       [0.97755944, 0.8102114 , 0.        , 1.0140332 , 0.55505716,
        0.9047815 ],
       [0.66658867, 1.13049335, 1.0140332 , 0.        , 1.0261739 ,
        0.5187482 ],
       [0.73973161, 0.79503927, 0.55505716, 1.0261739 , 0.        ,
        0.91703862],
       [0.5616437 , 1.19712465, 0.9047815 , 0.5187482 , 0.91703862,
        0.        ]])

In [15]:
sigma = np.sum(distancias, axis=0)/(centros.shape[0]-1)
sigma
#sigma=sum(dis[0])/(centros.tam -1)

array([0.80678865, 1.0042577 , 0.85232854, 0.87120746, 0.80660811,
       0.81986734])

# Salida capa OCULTA datos entrenamiento

In [16]:
#siempre indice 0
X_mlp_train = np.zeros((X_train.shape[0], centros.shape[0]), dtype=float)
#matriz de tamano train y centros
for i in range(X_train.shape[0]):
    for j in range(centros.shape[0]):
        #recorro train y sentros y ponfo en la matriz exp(-suma(train-centro)²)/(2*sigma²))  exp sum sigma
        X_mlp_train[i][j] = np.exp(-np.sum((X_train[i]-centros[j])**2)/(2.0*(sigma[j]**2)))
X_mlp_train.shape

(118, 6)

# Salida capa OCULTA datos test

In [17]:
X_mlp_test = np.zeros((X_test.shape[0], centros.shape[0]), dtype=float)
#lo mismo con test
for i in range(X_test.shape[0]):
    for j in range(centros.shape[0]):
        X_mlp_test[i][j] = np.exp(-np.sum((X_test[i]-centros[j])**2)/(2.0*(sigma[j]**2)))
X_mlp_test.shape

(60, 6)

## ADALINE con el Descenso del Gradiente Estocástico

In [18]:
from sklearn.linear_model import SGDClassifier

In [19]:
adaline = SGDClassifier(max_iter=5000)

adaline.fit(X_mlp_train, y_train)

print("Tasa de aciertos =", adaline.score(X_mlp_test, y_test))#score ambos test

Tasa de aciertos = 0.9333333333333333
