In [1]:
import pandas as pd

In [2]:
#crear dataframe
#data={"":[,,,]}

data = {
  "calories": [420, 380, 390,456],
  "duration": [50, 40, 45,44],
  "age": [34,23,31,23]
}

In [3]:
#crear dataframe desde datos
df = pd.DataFrame(data)

print(df) 

   calories  duration  age
0       420        50   34
1       380        40   23
2       390        45   31
3       456        44   23


In [4]:
#type()
print(type(df))
#df.shape
print(df.shape)

<class 'pandas.core.frame.DataFrame'>
(4, 3)


In [5]:
#primera columna
primera=df.iloc[:,0]
print(primera)


0    420
1    380
2    390
3    456
Name: calories, dtype: int64


In [6]:
primera1=df.iloc[:,0:2]#todas las filas de las columnas 0 a 2
print(primera1)


   calories  duration
0       420        50
1       380        40
2       390        45
3       456        44


In [7]:
primera2=df.iloc[1]#la primera fila
print(primera2)


calories    380
duration     40
age          23
Name: 1, dtype: int64


In [8]:
primera3=df.iloc[1:3]#filas 1 a 3 y todas las columnas
print(primera3)

   calories  duration  age
1       380        40   23
2       390        45   31


In [9]:
#eliminar columna
df1=df.drop(columns=["calories"])
print(df1)

   duration  age
0        50   34
1        40   23
2        45   31
3        44   23


In [2]:
import numpy as np

In [11]:
#crear array
#np.array([[,,,],[]])
arr = np.array([[0, 1, 2], [3, 4, 5]]) 

In [12]:
print(arr)

print(type(arr))

[[0 1 2]
 [3 4 5]]
<class 'numpy.ndarray'>


In [13]:
print(arr.shape)

(2, 3)


In [14]:
#reshape
array_nuevo=arr.reshape(3,2)
print(array_nuevo)

[[0 1]
 [2 3]
 [4 5]]


In [15]:
#convertir
df1=pd.DataFrame(array_nuevo,columns=["primer","segun"])

In [16]:
print(df1)

   primer  segun
0       0      1
1       2      3
2       4      5


In [17]:
#convertir
nmp=df1.to_numpy()
print(type(nmp))
print(nmp)

<class 'numpy.ndarray'>
[[0 1]
 [2 3]
 [4 5]]


In [3]:
z = np.array([[1, 2, 3, 4],
         [5, 6, 7, 8],
         [9, 10, 11, 12]])
z.shape


(3, 4)

In [4]:
print(type(z))
z=z.reshape(-1)
print(z)
z.shape

<class 'numpy.ndarray'>
[ 1  2  3  4  5  6  7  8  9 10 11 12]


(12,)

In [28]:
z=z.reshape(-1,1)#una sola caracteristica
print(z)
z.shape

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]


(12, 1)

In [29]:
z=z.reshape(1,-1)#una sola muestra
print(z)
z.shape

[[ 1  2  3  4  5  6  7  8  9 10 11 12]]


(1, 12)

In [9]:
#unique y argmax
x = np.array([23,45,32,45,3,81,3,45,3,2,12,23])
print(np.unique(x))
print(np.argmax(x))

[ 2  3 12 23 32 45 81]
5
