In [1]:
import pandas as pd

In [2]:
datos=pd.read_csv("convertido.csv")

In [3]:
datos

region.centroid.col  region.centroid.row  region.pixel.count   
0                     218                  178                   9  \
1                     113                  130                   9   
2                     202                   41                   9   
3                      32                  173                   9   
4                      61                  197                   9   
...                   ...                  ...                 ...   
2305                   30                  102                   9   
2306                  143                   24                   9   
2307                   80                   72                   9   
2308                   98                  133                   9   
2309                   19                  147                   9   

      short.line.density.5  short.line.density.2  vedge.mean  vegde.sd   
0                 0.111111                   0.0    0.833333  0.547722  \
1                 0.000000                   0.0    0.277778  0.250924   
2                 0.000000                   0.0    0.944448  0.772202   
3                 0.000000                   0.0    1.722220  1.781590   
4                 0.000000                   0.0    1.444440  1.515350   
...                    ...                   ...         ...       ...   
2305              0.000000                   0.0    1.222220  0.118518   
2306              0.000000                   0.0    1.277780  0.907406   
2307              0.000000                   0.0    1.222220  1.003700   
2308              0.000000                   0.0    0.555555  0.172133   
2309              0.000000                   0.0    0.222222  0.074074   

      hedge.mean  hedge.sd  intensity.mean  rawred.mean  rawblue.mean   
0       1.111110  0.544331       59.629600     52.44440      75.22220  \
1       0.333333  0.365148        0.888889      0.00000       2.55556   
2       1.111110  1.025600      123.037000    111.88900     139.77800   
3       9.000000  6.749490       43.592600     39.55560      52.88890   
4       2.611110  1.925460       49.592600     44.22220      61.55560   
...          ...       ...             ...          ...           ...   
2305    1.333330  0.800000       20.259300     20.33330      25.00000   
2306    0.888888  1.140750      127.630000    117.66700     141.66700   
2307    1.444440  1.167460       59.000000     51.33330      74.44440   
2308    0.388889  0.327731        0.962963      0.00000       2.77778   
2309    0.500000  0.077778        4.148150      3.88889       6.66667   

      rawgreen.mean  exred.mean  exblue.mean  exgreen.mean  value.mean   
0         51.222200  -21.555600     46.77780     -25.22220    75.22220  \
1          0.111111   -2.666670      5.00000      -2.33333     2.55556   
2        117.444000  -33.444400     50.22220     -16.77780   139.77800   
3         38.333300  -12.111100     27.88890     -15.77780    52.88890   
4         43.000000  -16.111100     35.88890     -19.77780    61.55560   
...             ...         ...          ...           ...         ...   
2305      15.444400    0.222222     14.22220     -14.44440    25.00000   
2306     123.556000  -29.888900     42.11110     -12.22220   141.66700   
2307      51.222200  -23.000000     46.33330     -23.33330    74.44440   
2308       0.111111   -2.888890      5.44444      -2.55556     2.77778   
2309       1.888890   -0.777778      7.55556      -6.77778     7.00000   

      saturation.mean  hue.mean      class  
0            0.318996  -2.04055       path  
1            1.000000  -2.12325    foliage  
2            0.199347  -2.29992        sky  
3            0.266914  -1.99886       path  
4            0.302925  -2.02227       path  
...               ...       ...        ...  
2305         0.381059  -1.55510  brickface  
2306         0.169397  -2.34925        sky  
2307         0.314606  -2.09022     cement  
2308         1.000000  -2.12325    foliage  
2309         0.

In [6]:
y=datos["class"]
y

0            path
1         foliage
2             sky
3            path
4            path
          ...    
2305    brickface
2306          sky
2307       cement
2308      foliage
2309    brickface
Name: class, Length: 2310, dtype: object

In [7]:
X=datos.drop(columns=["class"])
X

region.centroid.col  region.centroid.row  region.pixel.count   
0                     218                  178                   9  \
1                     113                  130                   9   
2                     202                   41                   9   
3                      32                  173                   9   
4                      61                  197                   9   
...                   ...                  ...                 ...   
2305                   30                  102                   9   
2306                  143                   24                   9   
2307                   80                   72                   9   
2308                   98                  133                   9   
2309                   19                  147                   9   

      short.line.density.5  short.line.density.2  vedge.mean  vegde.sd   
0                 0.111111                   0.0    0.833333  0.547722  \
1                 0.000000                   0.0    0.277778  0.250924   
2                 0.000000                   0.0    0.944448  0.772202   
3                 0.000000                   0.0    1.722220  1.781590   
4                 0.000000                   0.0    1.444440  1.515350   
...                    ...                   ...         ...       ...   
2305              0.000000                   0.0    1.222220  0.118518   
2306              0.000000                   0.0    1.277780  0.907406   
2307              0.000000                   0.0    1.222220  1.003700   
2308              0.000000                   0.0    0.555555  0.172133   
2309              0.000000                   0.0    0.222222  0.074074   

      hedge.mean  hedge.sd  intensity.mean  rawred.mean  rawblue.mean   
0       1.111110  0.544331       59.629600     52.44440      75.22220  \
1       0.333333  0.365148        0.888889      0.00000       2.55556   
2       1.111110  1.025600      123.037000    111.88900     139.77800   
3       9.000000  6.749490       43.592600     39.55560      52.88890   
4       2.611110  1.925460       49.592600     44.22220      61.55560   
...          ...       ...             ...          ...           ...   
2305    1.333330  0.800000       20.259300     20.33330      25.00000   
2306    0.888888  1.140750      127.630000    117.66700     141.66700   
2307    1.444440  1.167460       59.000000     51.33330      74.44440   
2308    0.388889  0.327731        0.962963      0.00000       2.77778   
2309    0.500000  0.077778        4.148150      3.88889       6.66667   

      rawgreen.mean  exred.mean  exblue.mean  exgreen.mean  value.mean   
0         51.222200  -21.555600     46.77780     -25.22220    75.22220  \
1          0.111111   -2.666670      5.00000      -2.33333     2.55556   
2        117.444000  -33.444400     50.22220     -16.77780   139.77800   
3         38.333300  -12.111100     27.88890     -15.77780    52.88890   
4         43.000000  -16.111100     35.88890     -19.77780    61.55560   
...             ...         ...          ...           ...         ...   
2305      15.444400    0.222222     14.22220     -14.44440    25.00000   
2306     123.556000  -29.888900     42.11110     -12.22220   141.66700   
2307      51.222200  -23.000000     46.33330     -23.33330    74.44440   
2308       0.111111   -2.888890      5.44444      -2.55556     2.77778   
2309       1.888890   -0.777778      7.55556      -6.77778     7.00000   

      saturation.mean  hue.mean  
0            0.318996  -2.04055  
1            1.000000  -2.12325  
2            0.199347  -2.29992  
3            0.266914  -1.99886  
4            0.302925  -2.02227  
...               ...       ...  
2305         0.381059  -1.55510  
2306         0.169397  -2.34925  
2307         0.314606  -2.09022  
2308         1.000000  -2.12325  
2309         0.713228  -1.47564  

[2310 rows x 19 columns]

In [8]:
from sklearn.preprocessing import LabelBinarizer
import numpy as np
d=LabelBinarizer().fit(np.unique(y)).transform(y)
d

array([[0, 0, 0, ..., 1, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 1, 0],
       ...,
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0]])

In [9]:
from sklearn.preprocessing import MinMaxScaler
minmax=MinMaxScaler()
X=minmax.fit_transform(X)

In [11]:
from sklearn.model_selection import train_test_split
X_train,X_test,d_train,d_test=train_test_split(X,d,test_size=1/3)

In [12]:
pred=np.zeros(d_test.shape)
pred


array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [13]:
from sklearn.linear_model import LinearRegression

In [19]:
for i in range(d_test.shape[1]):
    
    lin=LinearRegression()
    lin.fit(X_train,d_train[:,i])
    pred[:,i]=lin.predict(X_test)
pred_fin=np.argmax(pred,axis=1)
pred_fin
    

array([1, 3, 5, 6, 5, 6, 3, 0, 0, 4, 4, 5, 0, 2, 0, 0, 0, 2, 0, 3, 4, 0,
       4, 4, 6, 6, 4, 4, 5, 4, 5, 2, 6, 6, 2, 6, 5, 4, 3, 0, 3, 6, 2, 0,
       6, 3, 6, 4, 4, 4, 2, 4, 2, 4, 0, 5, 2, 6, 1, 5, 3, 0, 4, 5, 1, 5,
       0, 3, 4, 2, 2, 2, 5, 2, 3, 3, 6, 3, 2, 0, 6, 3, 4, 5, 4, 3, 0, 5,
       5, 0, 2, 3, 0, 3, 0, 0, 6, 5, 3, 4, 3, 2, 2, 3, 0, 5, 3, 4, 5, 2,
       3, 0, 0, 6, 4, 5, 1, 6, 2, 6, 0, 0, 6, 2, 5, 3, 5, 4, 0, 3, 1, 5,
       1, 5, 4, 2, 2, 4, 1, 6, 0, 2, 1, 0, 5, 2, 5, 6, 2, 6, 2, 4, 6, 0,
       0, 2, 2, 0, 2, 5, 3, 4, 3, 4, 0, 0, 1, 4, 5, 2, 4, 3, 3, 6, 2, 0,
       0, 4, 3, 1, 3, 4, 4, 4, 0, 2, 1, 1, 0, 3, 5, 0, 0, 6, 1, 3, 1, 1,
       5, 5, 1, 3, 4, 0, 2, 3, 6, 2, 6, 5, 5, 6, 2, 3, 6, 2, 2, 0, 3, 0,
       2, 6, 4, 3, 0, 3, 3, 4, 3, 3, 1, 0, 0, 4, 5, 3, 3, 5, 6, 4, 2, 4,
       0, 2, 6, 0, 2, 4, 0, 0, 2, 6, 3, 3, 4, 6, 6, 0, 2, 3, 0, 4, 4, 4,
       3, 5, 6, 4, 6, 4, 2, 2, 3, 1, 2, 4, 3, 6, 0, 6, 2, 6, 5, 4, 6, 2,
       1, 4, 4, 3, 0, 2, 3, 1, 2, 4, 4, 4, 0, 5, 4,

In [21]:
from sklearn.metrics import accuracy_score,confusion_matrix
print(accuracy_score(pred_fin,np.argmax(d_test,axis=1)))
print(confusion_matrix(pred_fin,np.argmax(d_test,axis=1)))

0.8402597402597403
[[105  20   1   0   0   0   1]
 [  0  42   1   0   0   0   5]
 [  0   4  97   0   0   0  31]
 [  0   0   0 117   0   0   0]
 [  0  30   0   1 107   0   3]
 [  0   3   0   0   0 105   0]
 [  0  12  11   0   0   0  74]]


In [22]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import StratifiedKFold

In [23]:
skf=StratifiedKFold(n_splits=10)

In [34]:
res=pd.DataFrame(columns=["fold","aciertos"])

In [35]:
k=0
for train_index,test_index in skf.split(X,y):
    log=LogisticRegression(solver="lbfgs",multi_class="auto")
    log.fit(X[train_index],y[train_index])
    prediccion=log.predict(X[test_index])
  
    res.loc[len(res)]=[k,accuracy_score(prediccion,y[test_index])]
    k+=1


c:\Users\jmlozanoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\jmlozanoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-lear

In [36]:
res

fold  aciertos
0   0.0  0.930736
1   1.0  0.909091
2   2.0  0.904762
3   3.0  0.900433
4   4.0  0.904762
5   5.0  0.917749
6   6.0  0.896104
7   7.0  0.891775
8   8.0  0.913420
9   9.0  0.874459

In [37]:
print(res["aciertos"].mean())

0.9043290043290042


In [56]:
#FYFLPA
aciertos=np.zeros(10)
comparacion=pd.DataFrame(columns=["originales","prediccion"])

In [58]:
from sklearn.preprocessing import LabelEncoder
lab=LabelEncoder()
corregidos=lab.fit_transform(y)
corregidos

array([4, 2, 5, ..., 1, 2, 0])

In [60]:
k=0

for train_index,test_index in skf.split(X,y):
    y_prediccion=np.zeros(d[test_index].shape)
    for i in range(d[test_index].shape[1]):
        lin=LinearRegression()
        lin.fit(X[train_index],d[train_index,i])
        y_prediccion[:,i]=lin.predict(X[test_index])
    
   
    maximos=np.argmax(y_prediccion,axis=1)
    originales=corregidos[test_index]
    comparacion["originales"]=originales
    comparacion["prediccion"]=maximos
    aciertos[k]=accuracy_score(comparacion["originales"],comparacion["prediccion"])
    
    k+=1

    

In [61]:
aciertos

array([0.89177489, 0.82251082, 0.84415584, 0.83549784, 0.87012987,
       0.85281385, 0.82251082, 0.83549784, 0.83116883, 0.85714286])